my_list = [1, 2, 3, 4, 5]
print("Original List:", my_list)
my_list.append(6)
print("After appending 6:", my_list)
my_list.insert(2, 10)
print("After inserting 10 at index 2:", my_list)
extension_list = [7, 8, 9]
my_list.extend(extension_list)
print("After extending with [7, 8, 9]:", my_list)
my_list.remove(4)
print("After removing 4:", my_list)
popped_value = my_list.pop(3)
print("Popped element at index 3:", popped_value)
print("List after popping at index 3:", my_list)
index_of_5 = my_list.index(5)
print("Index of 5:", index_of_5)
count_of_3 = my_list.count(3)
print("Count of 3:", count_of_3)
my_list.reverse()
print("Reversed List:", my_list)
my_list.sort()
print("Sorted List:", my_list)
copied_list = my_list.copy()
print("Copied List:", copied_list)
my_list.clear()
print("Cleared List:", my_list)

